import 'package:b_grids/theming/constants.dart';
import 'package:flutter/material.dart';

class BInputDecoration extends InputDecoration {
  const BInputDecoration({
    super.labelText,
    super.hintText,
    super.prefixIcon,
    super.suffixIcon,
    super.errorText,
    super.border,
    super.enabledBorder = const OutlineInputBorder(
      borderRadius: BorderRadius.all(
        Radius.circular(4.0),
      ),
      gapPadding: 4.0,
      borderSide: BorderSide(
        color: offGrey,
        width: 1.0,
      ),
    ),
    super.focusedBorder = const OutlineInputBorder(
      borderRadius: BorderRadius.all(
        Radius.circular(4.0),
      ),
      gapPadding: 4.0,
      borderSide: BorderSide(
        color: darkBlue,
        width: 1.0,
      ),
    ),
    super.errorBorder,
    super.focusedErrorBorder,
    super.disabledBorder,
    super.contentPadding,
    super.isDense = true,
    super.helperText,
    super.helperStyle,
    super.counter,
    super.counterText,
    super.counterStyle,
    super.errorStyle,
    super.floatingLabelBehavior,
    super.isCollapsed,
    super.prefix,
    super.prefixText,
    super.prefixStyle,
    super.suffix,
    super.suffixText,
    super.suffixStyle,
    super.prefixIconConstraints,
    super.suffixIconConstraints,
    super.errorMaxLines,
    super.alignLabelWithHint,
    super.constraints,
    super.enabled,
    super.error,
    super.fillColor,
    super.filled,
    super.focusColor,
    super.hoverColor,
    super.labelStyle,
    super.floatingLabelAlignment,
    super.floatingLabelStyle,
    super.helper,
    super.helperMaxLines,
    super.hintFadeDuration,
    super.hintMaxLines,
    super.hintStyle,
    super.hintTextDirection,
    super.icon,
    super.iconColor,
    super.label,
    super.prefixIconColor,
    super.semanticCounterText,
    super.suffixIconColor,
  });
}
